services:
  # Backend WebSocket Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: collabcanva-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=development
      - ALLOWED_ORIGINS=http://localhost:5173
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - backend_node_modules:/app/node_modules
    networks:
      - collabcanva-network
    restart: unless-stopped

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: collabcanva-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_WS_URL=ws://localhost:8080
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
      # Don't mount node_modules - let container use its own
    networks:
      - collabcanva-network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_node_modules:


networks:
  collabcanva-network:
    driver: bridge
