services:
  - type: web
    name: collabcanva-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: NODE_ENV=production node dist/server.js
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: ALLOWED_ORIGINS
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false


