services:
  - type: web
    name: collabcanva-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: ALLOWED_ORIGINS
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false

